const GET_ALL_DICOM =  'GET_ALL_DICOM';
const ADD_DICOM = 'ADD_DICOM';
const CREATE_DICOM = 'CREATE_DICOM'
const NEW_PREDICTIONS = 'NEW_PREDICTIONS'

export {GET_ALL_DICOM, ADD_DICOM, CREATE_DICOM, NEW_PREDICTIONS}

